### ISSUE TITLE
Spaces in path to python script cause an exception

### ISSUE THREAD

**Issue by greenwoodma** [GateNLP/gateplugin-Python#49]
At least under linux if there is a space in the path to the python script you are wanting to run then you get a file not found error when the controller execution started callback tries to load the script

```
/home/mark/Stance Detection/condaenv/bin/python: can't open file '"/home/mark/Stance Detection/StanceClassifier/gate_stance.py"': [Errno 2] No such file or directory
Got exception running the compile command: org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2)
gate.util.GateRuntimeException: Cannot run the python program, my have a syntax error
	at gate.plugin.python.PythonPr.whenStarting(PythonPr.java:845)
	at gate.plugin.python.PythonPr.controllerExecutionStarted(PythonPr.java:1041)
	at gate.creole.ConditionalSerialAnalyserController.invokeControllerExecutionStarted(ConditionalSerialAnalyserController.java:571)
	at gate.creole.ConditionalSerialAnalyserController.execute(ConditionalSerialAnalyserController.java:121)
	at gate.util.Benchmark.executeWithBenchmarking(Benchmark.java:291)
	at gate.gui.SerialControllerEditor$RunAction$1.run(SerialControllerEditor.java:1777)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by johann-petrak** [comment]
Thanks!
I use apache exec CommandLine to actually run the command because I assumed that that library would take care of proper quoting and escaping on all OS, but apparently that assumption was wrong. If we rely on the lib to quote correctly it does not work (on Linux) if I explicitly prevent quoting, it works.
The Javadoc does not help and the tutorial example (which is for Windows) does not work here either, so  have to investigate how to make this correctly work for all OS.

**Comment by greenwoodma** [comment]
could you not use `gate.util.ProcessManager` which I believe works properly across different OS? We've used it for plenty of odd apps in the past including on Windows.

**Comment by johann-petrak** [comment]
Yes, I use the ProcessManager approach in the gatelib-interaction anyways, which I used first, but using ProcessManager directly is incredibly clumsy and involved when one wants to do everything right and handle problems, timeouts etc properly (so e.g. AFAIR quoting has been done by the client and is not handled by the ProcessManager class), so I thought it would be better to use a well-tested high level API for that (also in order to figure out if the gatelib-interaction could use it instead of hacking everything for itself).

**Comment by johann-petrak** [comment]
Tested and seesms to work on Windows as well.
