### ISSUE TITLE
GateWorker fails to connect

### ISSUE THREAD

**Issue by mdorkhah** [GateNLP/gateplugin-Python#62]
I try to use Annie like the example in the slide

gs = GateWorker(gatehome="C:/Users/moham/miniconda3", java="C:/Program Files/Java/jre1.8.0_281/bin/java.exe")

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: gate/creole/Plugin
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetMethodRecursive(Unknown Source)
	at java.lang.Class.getMethod0(Unknown Source)
	at java.lang.Class.getMethod(Unknown Source)
	at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: gate.creole.Plugin
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more
2021-04-06 16:34:35,706|ERROR|py4j.java_gateway|An error occurred while trying to connect to the Java server (127.0.0.1:25333)
.
.
.
Py4JNetworkError: An error occurred while trying to connect to the Java server

**Comment by johann-petrak** [comment]
Are you sure that your GATE is installed in "C:/Users/moham/miniconda3"? I would assume this is the miniconda installation directory and you want instead something like "C:/Program Files/GATE_Developer_9.0" or similar.
One way to find the installation directory of Java GATE is to right click the GATE icon and use the directory shown in the "Start in" field or the directory in the "Target" field which contains the gate.exe program. 

Could you please specify the version of gatenlp and GATE you are using if the above does not help?

**Comment by mdorkhah** [comment]
> Are you sure that your GATE is installed in "C:/Users/moham/miniconda3"? I would assume this is the miniconda installation directory and you want instead something like "C:/Program Files/GATE_Developer_9.0" or similar.
> One way to find the installation directory of Java GATE is to right click the GATE icon and use the directory shown in the "Start in" field or the directory in the "Target" field which contains the gate.exe program.
> 
> Could you please specify the version of gatenlp and GATE you are using if the above does not help?

Thank you very much for your prompt response. Sorry, I'm very new to gate...
I changed the folder as the following:
gs = GateWorker(gatehome="C:/Program Files/GATE_Developer_9.0.1", java="C:/Program Files/Java/jre1.8.0_281/bin/java.exe")

still facing this error:
Trying to start GATE Worker on port=25333 host=127.0.0.1 log=false keep=false
PythonWorkerRunner.java: starting server with 25333/127.0.0.1/NvL-Ni9PXiCsXxGcBYdKwupNTRc/false
.
.
.
Exception: Could not start server, giving up

**Comment by johann-petrak** [comment]
Ah this is now a different situation, could you please copy the whole error message, even if it is quite long? 
The part you have copied shows that this time, unlike before, an attempt is made to start the GATE worker.
Please also provide the version of gatenlp you are using:
```
import gatenlp
print(gatenlp.__version__)
```

**Comment by mdorkhah** [comment]
> Ah this is now a different situation, could you please copy the whole error message, even if it is quite long?
> The part you have copied shows that this time, unlike before, an attempt is made to start the GATE worker.
> Please also provide the version of gatenlp you are using:
> 
> ```
> import gatenlp
> print(gatenlp.__version__)
> ```

Sure, my gatenlp version is "1.0.3.1", the whole error is as following:

Trying to start GATE Worker on port=25333 host=127.0.0.1 log=false keep=false
PythonWorkerRunner.java: starting server with 25333/127.0.0.1/NvL-Ni9PXiCsXxGcBYdKwupNTRc/false
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-25-2bdab475cd82> in <module>
      2 #gdoc1 = gs.createDocument("An example document mentioning Barack Obama and New York")
      3 
----> 4 gs = GateWorker(gatehome="C:/Program Files/GATE_Developer_9.0.1", java="C:/Program Files/Java/jre1.8.0_281/bin/java.exe")
      5 gs.loadMavenPlugin("uk.ac.gate.plugins", "annie", "9.0")
      6 gpipe = gs.loadPipelineFromPlugin("uk.ac.gate.plugins", "annie", "/resources/ANNIE_with_defaults.gapp")

~\miniconda3\lib\site-packages\gatenlp\gateworker.py in __init__(self, port, start, java, host, gatehome, platform, auth_token, use_auth_token, log_actions, keep, debug)
    356                     break
    357                 if line == "PythonWorkerRunner.java: server start NOT OK":
--> 358                     raise Exception("Could not start server, giving up")
    359                 print(line, file=sys.stderr)
    360             atexit.register(self.close)

Exception: Could not start server, giving up

**Comment by johann-petrak** [comment]
Maybe you have a GateWorker process from a previous attempt still running and occupying the default port number 25333?

Try to add the parameter `port=25334` or `port=25335`, e.g.:

`gw = GateWorker(gatehome="C:/Program Files/GATE_Developer_9.0.1", java="C:/Program Files/Java/jre1.8.0_281/bin/java.exe", port=25334) 
`
to start a new process that uses a different port number.

In order to avoid GateWorker processes staying around in the background, make sure to always run the `close()` method on the GateWorker instance (gatenlp tries to close automatically when the Python process exits but this does not always work properly, e.g. in a Jupyter notebook)

If GateWorker processes are running in the background and blocking ports, one should be able to use the system's tools to kill them (this is fairly easy in Linux: 
`ps aww  | grep java | grep gate.tools.gatenlpworker.GatenlpWorker | cut -f 1 -d" "`
gives all the process ids of those processes which can then be killed using `kill PROCESSID`

On Windows this is harder to achieve as the Task Manager does not show the full command line or allow to search for it. One possibility is:
`wmic process get ProcessId,CommandLine | findstr java | findstr gate.tools.gatenlpworker.GatenlpWorker`
and locate the process id in the output, then use 
`taskkill /F /PID PROCESSID`

Note that after successfully starting the GateWorker, the process id of the started process can be retrieved using `gw.gateprocess.pid`

**Comment by mdorkhah** [comment]
> Maybe you have a GateWorker process from a previous attempt still running and occupying the default port number 25333?
> 
> Try to add the parameter `port=25334` or `port=25335`, e.g.:
> 
> `gw = GateWorker(gatehome="C:/Program Files/GATE_Developer_9.0.1", java="C:/Program Files/Java/jre1.8.0_281/bin/java.exe", port=25334) `
> to start a new process that uses a different port number.
> 
> In order to avoid GateWorker processes staying around in the background, make sure to always run the `close()` method on the GateWorker instance (gatenlp tries to close automatically when the Python process exits but this does not always work properly, e.g. in a Jupyter notebook)
> 
> If GateWorker processes are running in the background and blocking ports, one should be able to use the system's tools to kill them (this is fairly easy in Linux:
> `ps aww | grep java | grep gate.tools.gatenlpworker.GatenlpWorker | cut -f 1 -d" "`
> gives all the process ids of those processes which can then be killed using `kill PROCESSID`
> 
> On Windows this is harder to achieve as the Task Manager does not show the full command line or allow to search for it. One possibility is:
> `wmic process get ProcessId,CommandLine | findstr java | findstr gate.tools.gatenlpworker.GatenlpWorker`
> and locate the process id in the output, then use
> `taskkill /F /PID PROCESSID`
> 
> Note that after successfully starting the GateWorker, the process id of the started process can be retrieved using `gw.gateprocess.pid`

Thank you very much.
Changing the port worked for me! Though, I have lots of questions especially about PAMPAC rules or using JAPE rules within Python :|

**Comment by johann-petrak** [comment]
OK, closing this issue.

In order to report issues related to the Python gatenlp package please use the issue tracker of that project: https://github.com/GateNLP/python-gatenlp/issues

For questions, please use the Help Q&A section of the discussion forum:  https://github.com/GateNLP/python-gatenlp/discussions/categories/help-q-a
